name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0" \
            "cmake;3.22.1" \
            "ndk;27.0.12077973"

      - name: Make gradlew executable
        working-directory: android-nle
        run: chmod +x gradlew

      - name: Build Debug APK
        working-directory: android-nle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-nle-debug
          path: app/build/outputs/apk/debug/*.apk
